### ISSUE TITLE
aes-kw: use en(de)crypt_with_backend methods to improve performance

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/key-wraps#15]
Right now `aes-kw` is implemented in terms of multiple calls to `en(de)crypt_block`. it's somewhat inefficient since on each call checks CPU features flag, not only it introduces unnecessary branching, but also prevent compiler from keeping data in registers across calls.

**Comment by jvdsn** [comment]
How would the wrap/unwrap function know which backend to choose to call `en(de)crypt_with_backend`? Ideally it should still be the "best" (e.g. accelerated) backend available.

**Comment by tarcieri** [comment]
FWIW the very nature of this construction and the associated security properties pretty much necessitates a very small number of blocks per message. Which is to say: it's only secure if the ciphertext is uniformly random key material.

In practice since it's used for wrapping symmetric keys, with a 128-bit key it will use 3 blocks per message (I think, double check me on that), and with a 256-bit key it will use 4 blocks per message. So I'm not sure microoptimizing for larger numbers of blocks is particularly useful.

**Comment by newpavlov** [comment]
>How would the wrap/unwrap function know which backend to choose to call en(de)crypt_with_backend?

Backend is chosen by the block cipher implementation, not its user. So it always will be "the best" one.

You effectively need to manually write a rank-2 closure (i.e. implement the [`BlockClosure`](https://docs.rs/cipher/latest/cipher/trait.BlockClosure.html) trait) which accepts a [backend](https://docs.rs/cipher/latest/cipher/trait.BlockBackend.html). The meat of the key wrap/unwrap algorithm will look mostly the same. The main difference will be that instead of calling `encrypt_block`/`decrypt_block` you would call the `proc_block` method on backend passed to the closure.

>probably not worth complicating the API over.

Public API of the crate will not change in any way. The inner working will become a bit more boilerplat-y, but additional complexity should be quite manageable. Though I agree that this issue has a really low priority.

If Rust had proper rank-2 closure support (i.e. using the `|backend| { .. }` syntax), amount of boilerplate would have been significantly smaller. :(

**Comment by tarcieri** [comment]
Fixed in #19
